
import java.awt.Desktop;
import java.io.File;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.Properties;
import javax.swing.JOptionPane;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;
import org.jdatepicker.impl.JDatePanelImpl;
import org.jdatepicker.impl.JDatePickerImpl;
import org.jdatepicker.impl.UtilDateModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ricardoi
 */
public class NuevaFCam extends javax.swing.JInternalFrame implements TableModelListener {
    private Map<String, String> opciones;
    private ArrayList falta= new ArrayList();
    private boolean enviando=false;
    private JDatePickerImpl datePicker;
    private Float sumatotal;

    /**
     * Creates new form NuevaFactura
     */
    public NuevaFCam() {
        initComponents();
        TableColumnModel m = jTable1.getColumnModel();
        m.getColumn(0).setMaxWidth(70);
        m.getColumn(1).setMaxWidth(580);
        m.getColumn(2).setMaxWidth(70);
        m.getColumn(3).setMaxWidth(140);
        m.getColumn(4).setMaxWidth(140);
iniciarData();
this.add(datePicker);
        
        jTable1.getModel().addTableModelListener(this);
        
    }
    
    private void iniciarData(){
        opciones = BDLocal.getOpciones();
        jTextField2.setText(opciones.get("fcam_resolucion"));
        jTextField3.setText(opciones.get("fcam_serie"));
        jTextField1.setText(opciones.get("fcam_actual"));
        jTextField4.setText(opciones.get("empresa_codigo"));
        jTextField5.setText(opciones.get("empresa_sucursal"));
        jTextField6.setText(opciones.get("empresa_caja"));
        Date fecha = new Date();
        SimpleDateFormat df = new SimpleDateFormat("dd/MM/YYYY");
        jLabel20.setVisible(false);
        
UtilDateModel model = new UtilDateModel();
        Calendar hoy = new GregorianCalendar();
model.setDate(hoy.get(Calendar.YEAR),hoy.get(Calendar.MONTH),hoy.get(Calendar.DAY_OF_MONTH));
model.setSelected(true);
// Need this...
Properties p = new Properties();
p.put("text.today", "Today");
p.put("text.month", "Month");
p.put("text.year", "Year");
JDatePanelImpl datePanel = new JDatePanelImpl(model, p);
// Don't know about the formatter, but there it is...
 datePicker = new JDatePickerImpl(datePanel, new DateLabelFormatter());
datePicker.setBounds(215, 82, 150, 100);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel23 = new javax.swing.JLabel();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();

        setClosable(true);

        jLabel1.setText("No. Factura");

        jLabel2.setText("Resolución");

        jLabel3.setText("ID Serie");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Empresa");

        jLabel5.setText("Sucursal");

        jLabel6.setText("Caja");

        jLabel7.setText("Usuario");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "GTQ", "USD" }));
        jComboBox1.setSelectedItem("GTQ");

        jLabel8.setText("Moneda");

        jLabel9.setText("Tasa cambio");

        jTextField8.setText("1");

        jLabel10.setText("Generación");

        jLabel11.setText("Fecha emisión");

        jLabel12.setText("Contribuyente");

        jLabel13.setText("Dirección");

        jLabel14.setText("Nit contribuyente");

        jLabel15.setText("Valor Neto");

        jLabel16.setText("IVA");

        jLabel17.setText("Total");

        jLabel18.setText("Descuento");

        jLabel19.setText("Exento");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Cantidad", "Descripción", "Métrica", "Precio U.", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "O", "C" }));

        jLabel20.setText("Enviando información....");

        jLabel21.setText("DPI");

        jTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField9ActionPerformed(evt);
            }
        });

        jLabel22.setText("ISR");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "5%", "7%" }));

        jLabel23.setText("Impuesto");

        jLabel24.setText("Total en letras:");

        jLabel25.setText("Periodo");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "30 dias", "60 dias" }));

        jCheckBox1.setText("Es exportación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField12))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel7)
                                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel3)
                                        .addGap(101, 101, 101)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(154, 154, 154)
                                        .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE)
                                .addComponent(jTextField8)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jComboBox2, 0, 129, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextField5))
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel19)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(148, 148, 148))
                            .addComponent(jTextField16)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField20))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel21)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel22)
                            .addGap(18, 18, 18)
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel23)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jCheckBox1))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel14)
                                .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, 783, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel25))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23)
                    .addComponent(jTextField19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel18)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jLabel20))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(!enviando){
ArrayList ArrDatos = new ArrayList();
sumatotal = 0.0f;
        for(int i=0;i<jTable1.getRowCount();i++){
            String dat = (String)jTable1.getValueAt(i, 1);
            if((dat!=null)&&(dat.length()>0)){
                Map<String,String> linea = new HashMap<String,String>();
                String q = (String)jTable1.getValueAt(i,0);
                if((q==null)||(q.matches(""))) q = "0";
                linea.put("quantity",q);
                linea.put("description",(String)jTable1.getValueAt(i,1));
                q = (String)jTable1.getValueAt(i,2);
                if((q==null)||(q.matches(""))) q = "UNI";
                linea.put("metric",q);
                q = (String)jTable1.getValueAt(i,3);
                if((q==null)||(q.matches(""))) q = "0";
                linea.put("unitprice",q);
               q = (String)jTable1.getValueAt(i,4);
                if((q==null)||(q.matches(""))) q = "0";
                linea.put("totalvalue",q);
                sumatotal = roundDoubleTwoDecimals(sumatotal + Float.valueOf(q));
                ArrDatos.add(linea);
            }
        }
        if(ArrDatos.size()>0 && valido()){
        enviando=true;
        jLabel20.setVisible(true);
        
        Thread updateThread = new Thread() {
                public void run() {
        Map<String,String> params = new HashMap<String,String>();
        params.put("nofactura",jTextField1.getText());
        params.put("resolucion",jTextField2.getText());
        params.put("idserie",jTextField3.getText());
        params.put("empresa",jTextField4.getText());
        params.put("sucursal",jTextField5.getText());
        params.put("caja",jTextField6.getText());
        params.put("usuario",jTextField7.getText());
        params.put("moneda",(String)jComboBox1.getSelectedItem());
        params.put("tasacambio",jTextField8.getText());
        params.put("generacion",(String)jComboBox2.getSelectedItem());
        Date cal = (Date)datePicker.getModel().getValue();
        SimpleDateFormat format1 = new SimpleDateFormat("dd/MM/yyyy");
        params.put("fechaemision",format1.format(cal.getTime()));
        params.put("nombrecontribuyente",jTextField11.getText());
        params.put("direccioncontribuyente",jTextField12.getText());
        if(jCheckBox1.isSelected()){
            params.put("nitexportacion",jTextField13.getText());
            params.put("nitcontribuyente","cf");
        }else{
            params.put("nitexportacion"," ");
            params.put("nitcontribuyente",jTextField13.getText());
        }
        params.put("valorneto",jTextField14.getText());
        params.put("iva",jTextField15.getText());
        params.put("total",jTextField16.getText());
        params.put("descuento",jTextField17.getText());
        params.put("exento",jTextField18.getText());
        params.put("dpi",jTextField9.getText());
        params.put("porcentaje",(String)jComboBox3.getSelectedItem());
        String isr = jTextField19.getText();
        if(isr.trim().length()<=0){
            isr = "0.0";
        }
        params.put("totalisr",String.valueOf(roundDoubleTwoDecimals(Float.valueOf(isr))));
        params.put("totalletras",jTextField20.getText());
        params.put("periododias",(String)jComboBox4.getSelectedItem());
        ArrayList ArrDatos = new ArrayList();
        for(int i=0;i<jTable1.getRowCount();i++){
            String dat = (String)jTable1.getValueAt(i, 1);
            if((dat!=null)&&(dat.length()>0)){
                /*Map<String,String> linea = new HashMap<String,String>();
                linea.put("quantity",(String)jTable1.getValueAt(i,0));
                linea.put("description",(String)jTable1.getValueAt(i,1));
                linea.put("metric",(String)jTable1.getValueAt(i,2));
                linea.put("unitprice",(String)jTable1.getValueAt(i,3));
                linea.put("totalvalue",(String)jTable1.getValueAt(i,4));
                ArrDatos.add(linea);*/
                Map<String,String> linea = new HashMap<String,String>();
                String q = (String)jTable1.getValueAt(i,0);
                if((q==null)||(q.matches(""))) q = "0";
                linea.put("quantity",q);
                q = (String)jTable1.getValueAt(i,1);
                if((q==null)) q = "";
                linea.put("description",q);
                q = (String)jTable1.getValueAt(i,2);
                if((q==null)||(q.matches(""))) q = "UNI";
                linea.put("metric",q);
                q = (String)jTable1.getValueAt(i,3);
                if((q==null)||(q.matches(""))) q = "0";
                linea.put("unitprice",q);
               q = (String)jTable1.getValueAt(i,4);
                if((q==null)||(q.matches(""))) q = "0";
                linea.put("totalvalue",q);
                sumatotal = roundDoubleTwoDecimals(sumatotal + Float.valueOf(q));
                ArrDatos.add(linea);
            }
        }
        String respuesta = APIGeface.enviarDataFcam(params,ArrDatos);
        String archivo = Registro.procesaArchivo(respuesta);
        if((archivo!="")&&(!archivo.startsWith("error"))){ 
            int correlativo = Integer.valueOf(opciones.get("fcam_actual"));
            int maximo = Integer.valueOf(opciones.get("fcam_final"));
            if(correlativo<maximo){
                opciones.put("fcam_actual", String.valueOf(correlativo+1));
                if(BDLocal.saveOpciones(opciones)){

                }else{
                    JOptionPane.showMessageDialog(null, "No se guardaron las opciones");
                }
            }
            jLabel20.setVisible(false);
            Object[] opciones = {"Ver documento","Cancelar"};
            int r = JOptionPane.showOptionDialog(null, "Documento creado","Operación exitosa",JOptionPane.YES_NO_OPTION,JOptionPane.INFORMATION_MESSAGE,null,opciones,opciones[0]);
            if(r==JOptionPane.YES_NO_OPTION){
                Desktop d = Desktop.getDesktop();
                File f = new File(archivo);
                try{
                    d.open(f);
                }catch(Exception e){
                    System.out.println("Abrir archivo");
                }
            }
            reiniciar();
        }else{
JOptionPane.showMessageDialog(null, "Se generó un error:"+archivo);
        }
        enviando=false;
        jLabel20.setVisible(false);
                }
        };
        updateThread.start();
        }else{
            String faltan = "";
            if(ArrDatos.size()<=0){
                faltan = "-No ha ingresado productos a facturar";
            }
            for(int i = 0;i<falta.size();i++){
                if(i>0){
                    faltan = faltan + "\r\n";
                }
                faltan = faltan + "-"+(String)falta.get(i);
            }
            JOptionPane.showMessageDialog(null, "Ingrese los datos solicitados:\r\n"+faltan);
            falta.clear();
        }
        }else{
                JOptionPane.showMessageDialog(null, "Los datos están siendo enviados");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField9ActionPerformed

    public static int roundDoubleToUpperInt(double d){
    return (d%1==0.0f)?(int)d:(int)(d+1);
}
    
public static Float roundDoubleTwoDecimals(float f){
DecimalFormat decimalFormat = new DecimalFormat("#.##");
    return Float.valueOf(decimalFormat.format(f)); // output is 102.24
}
    
    public void tableChanged(TableModelEvent e){
        int row = e.getFirstRow();
        int col = e.getColumn();
        TableModel model = (TableModel)e.getSource();
        Object data = model.getValueAt(row,col);
        if(col==0){
            Object o = model.getValueAt(row,3);
            if(o!=null && data!=null){
                String num = (String)o;
                String num2 = (String)data;
                if(num.matches("-?\\d+(\\.\\d+)?") && num2.matches("-?\\d+(\\.\\d+)?")){
                    Float precio = Float.valueOf((String)o);
                    if(precio>0){
                        model.setValueAt((Object)String.valueOf(roundDoubleTwoDecimals(precio*Float.valueOf((String)data))), row, 4);
                    }
                }
            }
        }
        if(col==1){

        }
        if(col==3){
            Object o = model.getValueAt(row,0);
            if(o!=null){
                String num = (String)o;
                String num2 = (String)data;
                if(num.matches("-?\\d+(\\.\\d+)?") && num2.matches("-?\\d+(\\.\\d+)?")){
                    Float unidades = Float.valueOf(num);
                    if(unidades>0){
                        model.setValueAt((Object)String.valueOf(roundDoubleTwoDecimals((unidades*Float.valueOf(num2)))), row, 4);
                    }
                }
            }
        }
        if(col==4){
            
        }
    }
    
    public boolean valido(){

        boolean res = true;
        if((" "+jTextField1.getText()).trim().length()<=0){
            res=false;
            falta.add("No. Factura");
        }
        if((" "+jTextField2.getText()).trim().length()<=0){
            res=false;
            falta.add("Resolución");
        }
        if((" "+jTextField3.getText()).trim().length()<=0){
            res=false;
            falta.add("ID Serie");
        }
        if((" "+jTextField4.getText()).trim().length()<=0){
            res=false;
            falta.add("ID Empresa");
        }
        if((" "+jTextField7.getText()).trim().length()<=0){
            res=false;
            falta.add("Usuario");
        }
        if((" "+jTextField8.getText()).trim().length()<=0){
            res=false;
            falta.add("Tasa de cambio");
        }

        if(!datePicker.getModel().isSelected()){
            res=false;
            falta.add("Fecha emisión");
        }
        if((" "+jTextField13.getText()).trim().length()<=0){
            res=false;
            falta.add("Nit Contribuyente");
        }
        if((" "+jTextField14.getText()).trim().length()<=0){
            if(jTextField18.getText().trim().length()<=0){        //Si no hay cantidad exento
                res=false;
                falta.add("Valor Neto");
            }
        }
        if((" "+jTextField15.getText()).trim().length()<=0){
            if(jTextField18.getText().trim().length()<=0){        //Si no hay cantidad exento
                res=false;
                falta.add("IVA");
            }
        }
        
        if((" "+jTextField16.getText()).trim().length()<=0){
            res=false;
            falta.add("TOTAL");
        }else{
            String txtTotal = jTextField16.getText();
            Float fTotal = Float.valueOf(txtTotal);
            if(sumatotal.compareTo(fTotal)!=0){
                res=false;
                falta.add("Suma de productos no concuerda con total a facturar");
            }
        }
        if((" "+jTextField20.getText()).trim().length()<=0){
            res=false;
            falta.add("Total en letras");
        }
        Float exento = Float.valueOf("0"+jTextField18.getText());
        Float total = Float.valueOf("0"+jTextField16.getText());
        Float iva = Float.valueOf("0"+jTextField15.getText());
        Float neto = Float.valueOf("0"+jTextField14.getText());
        if(total!=(iva+neto)){
            if(total.compareTo(exento)!=0){
            res=false;
            JOptionPane.showMessageDialog(null, "El total no coincide");
            }
        }
        return res;
    }
    
    public void reiniciar(){
    jTable1.removeAll();
    DefaultTableModel dm = (DefaultTableModel) jTable1.getModel();
    int rowCount = dm.getRowCount();
    //Remove rows one by one from the end of the table
    for (int i = rowCount - 1; i >= 0; i--) {
        dm.setValueAt("",i, 0);
        dm.setValueAt("",i, 1);
        dm.setValueAt("",i, 2);
        dm.setValueAt("",i, 3);
        dm.setValueAt("",i, 4);
    }
    jTextField1.setText("");
    jTextField11.setText("");
    jTextField12.setText("");
    jTextField13.setText("");
    jTextField14.setText("");
    jTextField15.setText("");
    jTextField16.setText("");
    jTextField17.setText("");
    jTextField18.setText("");
    jTextField19.setText("");
    jTextField20.setText("");
    jTextField7.setText("");
    jTextField8.setText("");
    jTextField9.setText("");
    jCheckBox1.setSelected(false);
iniciarData();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
